CREATE TABLE IF NOT EXISTS engine (
    id INTEGER NOT NULL AUTO_INCREMENT,
    style VARCHAR(30) NOT NULL,
    cc INTEGER NOT NULL,
    power INTEGER NOT NULL,
    car INTEGER NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS car (
    id INTEGER NOT NULL AUTO_INCREMENT,
    engine_id INTEGER NOT NULL,
    make VARCHAR(30) NOT NULL,
    model VARCHAR(30) NOT NULL,
    registration VARCHAR(30) NOT NULL,
    FOREIGN KEY (engine_id) REFERENCES engine(id),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;